### ISSUE TITLE
Composer requirements

### ISSUE THREAD

**Issue by donatj** [tholu/php-cidr-match#1]
The composer.json states this requires the curl and json extensions - is this accurate, I don't see them used?

**Comment by donatj** [comment]
Also, would you be inclined to tag a release? ;) I'd like to use this with composer but requiring dev-master is far from ideal.

**Comment by tholu** [comment]
You are right, this is still quick and dirty - I will fix composer.json and release a 0.1 afterwards as soon as possible.

**Comment by tholu** [comment]
Fixed now, if you have more suggestions, just let me know!

**Comment by donatj** [comment]
Thank you! I just needed something quick and dirty that would do v4 and v6 and this fit the bill.
