### ISSUE TITLE
The ipv4 doesn't work correctly.

### ISSUE THREAD

**Issue by thellimist** [tholu/php-cidr-match#2]
I ran the following tests and they did not result correctly. For example `$this->assertTrue($cidrMatch->match($addr, '10.0.0.1/8'));` is `True` but it returns `False`.

```
        $cidrMatch = new CIDRmatch();
        // $this->assertTrue($cidrMatch->match($addr, '10.0.0.1/8'));
        // $this->assertTrue($cidrMatch->match($addr, '10.0.0.10/8'));
        // $this->assertTrue($cidrMatch->match($addr, '10.5.5.0/16'));
        // $this->assertFalse($cidrMatch->match($addr, '10.4.5.0/16'));
        // $this->assertTrue($cidrMatch->match($addr, '10.4.5.0/15'));
```

[Symfony/IpUtils](https://github.com/symfony/http-foundation/blob/master/IpUtils.php) has a good test coverage and works perfectly. Recommend using that one.

**Comment by tholu** [comment]
@thellimist What's `$addr` in your test cases, so I can check what exactly went wrong here? I recommend IpUtils in the README already.

**Comment by thellimist** [comment]
Sorry I forgot to paste that. I deleted the code so I won't be able to tell you but you can use these tests to check if your code is working as intended.

https://github.com/cloudflare/cf-ip-rewrite/blob/master/tests/IpUtilsTest.php
